version: '3'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./certbot/www:/usr/share/nginx/html/.well-known/acme-challenge
      - ./certbot/conf:/etc/letsencrypt
    restart: always
